version: '3.7'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0 --port=80'
        volumes:
            - .:/app
        ports:
            - 80:80
        depends_on: 
            - db
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: enuygun
            MYSQL_USER: enuygun
            MYSQL_PASSWORD: enuygun
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        security_opt:
            - seccomp:unconfined